### ISSUE TITLE
Use tag names

### ISSUE THREAD

**Issue by niba** [will-lynas/grapple-line.nvim#4]
I use tags to differentiate similar file names. Status should pick the tag name over combo: index + filename

**Comment by will-lynas** [comment]
Thanks for the suggestion! Would you mind giving an example of how you use grapple, and how you would want the status line to look?

**Comment by niba** [comment]
I don't use anything fancy beside custom tags and git_branch as scope features. I have my own statusline function and in my programming world (react, typescript) filenames and paths are very often similar like (page, layout, etc) that's why I very often create custom tag names. You should check if tag has custom name and if has then use it (or at least make it configurable)

I forgot that for grapple a tag is a general term for bookmark. I just want to display custom tag names (tag.name) when is available.

**Comment by will-lynas** [comment]
Got it, thanks! I'll look into adding that.

**Comment by will-lynas** [comment]
@niba I've got a PR up. Does this change fit your workflow?

**Comment by niba** [comment]
@will-lynas  I tested your changes. Everything is perfect now. Thanks!

**Comment by will-lynas** [comment]
Great, I'll get that merged.
